[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = {version = "0.7", features = ["csr"]}
web-sys = "0.3"
wasm-bindgen = "0.2"
binlayout = {path = "../binlayout/"}
gloo = "0.11.0"
anyhow = "1"
