[package]
name = "server"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = "0.8"
tower-http = { version = "0.6", features = ["fs"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
